#Jekyll config file

#title of site
name: Project RFP-EZ

#description of site
description: Software platform to make buying web work better for everyone

#URL of site, include http://, do not include a trailing slash
url: http://presidential-innovation-fellows.github.com/rfpez-blog

#files to exclude, array
exclude: [ 'readme.md', 'php' ]

#posts per page
paginate: 5

#number of items in RSS feed
rss_limit: 10

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

#whether production or dev, minifies JS, bool
production: true

#prose config, see http://prose.io/help/handbook.html
prose:
  rooturl: "_posts"
  metadata:
    "_posts": |
      title: "Title of the post"
      description: "SEO friendly description"
      author: "Your Name Here"
      layout: post
      comments: true
      category:
      tags:
      published: false

#twitter handle for widget
twitter:
  username: "projectrfpez"
  count: 5

#github widget
github:
  repo: "presidential-innovation-fellows/sowcomposer"
  count: 5

#disqus username
disqus_shortname: 'rfpez'

#google analytics username
ga_username: 'UA-34330943-1'